Round 2 of Inspection for LNet Integration
* Use 0@lo as default end point address
* Use lctl list_nids to get register LNI in c2t1fs st
* Change copyright year to 2012
* Instead of commenting, enclose the code that uses deprecated interfaces
  in #if 0 ... #endif
* Remove deprecated interfaces, files

diff --git a/c2t1fs/linux_kernel/st/common.sh.in b/c2t1fs/linux_kernel/st/common.sh.in
--- a/c2t1fs/linux_kernel/st/common.sh.in
+++ b/c2t1fs/linux_kernel/st/common.sh.in
@@ -31,7 +31,7 @@ modload_galois()
 
 modunload_galois()
 {
-	rmmod galois
+	rmmod galois &>> /dev/null
 }
 
 modload()
@@ -46,6 +46,6 @@ modunload()
 	for m in $MODLIST ;do
 		echo $m
 	done | tac | while read ;do
-		rmmod $REPLY || echo "Error unloading $m."
+		rmmod $REPLY &>> /dev/null || echo "Error unloading $m."
 	done
 }
