The new ADDB introduced
The new ADDB (Analysis and Diagnostic Data Base) framework
is introduced. What's new about ADDB (quotes from HLD):

 * C macro based record definition interface with support for
   multiple fields.
 * Registration of ADDB records required to support 3rd party
   extensibility.
 * Compile time validation of posted records.
 * Additional semantics for ADDB contexts:
   - Concepts including context categories, context types, and
     context identifiers;
   - Operations including storage, retrieval, conveyance and import.
 * Support for ADDB counters with some intrinsic statistical
   capabilities.
 * Mero STOBs used for ADDB repositories.
 * Efficient representation of ADDB records in persistent storage.
   Meta-data is not duplicated and all fields of ADDB records are
   numeric.
 * APIs to read ADDB context and event records from a repository, and
   a CLI to dump ADDB records in a repository (m0addbdump).
 * An ADDB machine as a unifying implementation construct is introduced.

The following item is ongoing:

 * Efficient conveyance of ADDB records from nodes that do not have
   persistent ADDB storage to those that do, via the RPC subsystem.
   Use a pull model as opposed to the existing push model.

See HLD at http://goo.gl/J2sEK .
See DLD at addb/addb.h and addb/addb_pvt.h along with
           Functional Specification and usage examples.

This change is the result of addb-dev branch (at 69fc5f4) merge.

Acked-by: Carl Braganza <carl_braganza@xyratex.com>

Bloated-by:
<size>
    text     data      bss    total filename
   77495    14040     5808    97343 libmero.so
   88289    11040    12832   112161 m0mero.ko
   83925    13696     5840   103461 libmero-altogether.so
</size>

diff --git a/m0t1fs/linux_kernel/st/common.sh.in b/m0t1fs/linux_kernel/st/common.sh.in
--- a/m0t1fs/linux_kernel/st/common.sh.in
+++ b/m0t1fs/linux_kernel/st/common.sh.in
@@ -6,6 +6,12 @@
 
 MODLIST="@ABS_SRCDIR@/build_kernel_modules/m0mero.ko"
 
+# The following associative array carries the list of module parameters for
+# modules in MODLIST.
+typeset -A MODPARAMS
+NULL_UUID="00000000-0000-0000-0000-000000000000"
+MODPARAMS[m0mero.ko]="node_uuid=${NODE_UUID:-$NULL_UID}"
+
 abort()
 {
 	msg="$1"
@@ -37,7 +43,12 @@ modunload_galois()
 modload()
 {
 	for m in $MODLIST ;do
-		insmod $m || abort "Error loading $m."
+                BN=$(basename $m)
+                PARAMS=
+                if [[ ! -z "${MODPARAMS[$BN]}" ]] ; then
+		    PARAMS=${MODPARAMS[$BN]}
+		fi
+		insmod $m $PARAMS || abort "Error loading $m $PARAMS"
 	done
 }
 
