net-test: landed bulk and kernel testing
ST: net/test/st/st.sh
Demo: net/test/demo/demo.sh

Reviewed-on: https://reviewboard.clusterstor.com/r/1108/
Reviewed-by: Carl Braganza <carl_braganza@xyratex.com>
Reviewed-by: Dave Cohrs <dave_cohrs@xyratex.com>

Reviewed-on: https://reviewboard.clusterstor.com/r/1228/
Reviewed-by: Carl Braganza <carl_braganza@xyratex.com>
Reviewed-by: Dave Cohrs <dave_cohrs@xyratex.com>

Reviewed-on: https://reviewboard.clusterstor.com/r/1285/
Reviewed-by: Carl Braganza <carl_braganza@xyratex.com>
Reviewed-by: Dave Cohrs <dave_cohrs@xyratex.com>
Reviewed-by: Andriy Tkachuk <andriy_tkachuk@xyratex.com>

Reviewed-on: https://reviewboard.clusterstor.com/r/1253/
Reviewed-by: Carl Braganza <carl_braganza@xyratex.com>
Reviewed-by: Dave Cohrs <dave_cohrs@xyratex.com>

Reviewed-on: https://reviewboard.clusterstor.com/r/1295/
Reviewed-by: Carl Braganza <carl_braganza@xyratex.com>
Reviewed-by: Dave Cohrs <dave_cohrs@xyratex.com>

Bloated-by:

<size>
    text     data      bss    total filename
      48        0        0       48 libmero.so
   31820     -192    57536    89164 m0mero.ko
    -256        0        0     -256 libmero-altogether.so
</size>

diff --git a/m0t1fs/linux_kernel/st/common.sh.in b/m0t1fs/linux_kernel/st/common.sh.in
--- a/m0t1fs/linux_kernel/st/common.sh.in
+++ b/m0t1fs/linux_kernel/st/common.sh.in
@@ -57,6 +57,6 @@ modunload()
 	for m in $MODLIST ;do
 		echo $m
 	done | tac | while read ;do
-		rmmod $REPLY &>> /dev/null || echo "Error unloading $m."
+		rmmod $REPLY &>> /dev/null || echo "Error unloading $REPLY."
 	done
 }
