MERO-2570: return and check the result of unprepare()
Errors now can be passed to the caller scripts which can
report error to user.

Change-Id: Icc69e7436caef2f1b9cbad57130ced0ef96c643e

diff --git a/m0t1fs/linux_kernel/st/common.sh.in b/m0t1fs/linux_kernel/st/common.sh.in
--- a/m0t1fs/linux_kernel/st/common.sh.in
+++ b/m0t1fs/linux_kernel/st/common.sh.in
@@ -69,9 +69,14 @@ modload()
 modunload()
 {
 	local m
+	local rc=0
 	for m in $MODLIST; do
 		echo $m
 	done | tac | while read; do
-		rmmod $REPLY &> /dev/null || echo "Error unloading $REPLY." >&2
+		rmmod $REPLY &> /dev/null || {
+			rc=$?
+			echo "Error unloading $REPLY." >&2
+		}
 	done
+	return $rc
 }
