build: verify *_xc.[hc] files don't sneak into EXTRA_DIST
Auto-generated files mustn't get into dist archive, otherwise it may
result in invalid build.

Change-Id: Ifda43e4d780808bff6114e2ba1b9e102fb0f7717

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1097,6 +1097,14 @@ check-make-prebuild:
 			echo "Please, move them into nodist_mero_libmero_la_SOURCES var instead."; \
 			exit 1; \
 		fi
+	@XC=`echo "$(EXTRA_DIST)" | grep -Po '\S+_xc\.[ch]'` ; \
+		if [[ -n $$XC ]] ; then \
+			echo FAIL; \
+			echo "ERROR: xcode files found in EXTRA_DIST makefile variable:"; \
+			echo "$$XC"; \
+			echo "Please, remove them from EXTRA_DIST."; \
+			exit 1; \
+		fi
 	@echo 'OK'
 
 .PHONY: check-sources-prebuild
