m0kdump2trace: doen't rely on mero logs in dmesg
Improve mechanism which is used to extract Mero's kernel-mode trace
buffer from a kernel crashdump. It doesn't rely on the m0mero.ko log
messages with trace-related information to be available in a dmesg
buffer. Instead it's based on the extraction of such information
directly from the dumped kernel memory, locating it by a known magic
identifier.

In addition, there are two new options for m0kdump2trace utility:

  -a|--address <addr>

          In memory address of either a trace buffer or a module image
          (if '-m|--module-image' is provided).

  -s|--size <size>

          Size of the module image, effective only when
          '-m|--module-image' is provided.

Change-Id: I2ef78785e41c36c9fed0b8a8866372abbf4bbdb6

diff --git a/utils/trace/m0kdump2trace b/utils/trace/m0kdump2trace
--- a/utils/trace/m0kdump2trace
+++ b/utils/trace/m0kdump2trace
@@ -20,6 +20,8 @@ readonly vmlinux="/usr/lib/debug/lib/modules/$(uname -r)/vmlinux"
 verbose=false
 force=false
 module_img=false
+address=
+size=
 cli_args=
 infile=$stdin
 outfile=$stdout
@@ -39,14 +41,16 @@ usage()
 {
     cat <<USAGE_END
 Usage: $PROG_NAME [-h|--help] [-v|--verbose] [-f|--force] [-m|--module-image]
-                  [vmcore] [trace_buffer|module_image]
+                  [-a|--address addr] [-s|--size size]
+                  [[vmcore] [output-file]]
 
-  Arguments are optional. If not specified, STDIN and STDOUT are used by default.
+  Arguments are optional. If not specified, STDIN and STDOUT are used for
+  <vmcore> and <output-file> respectively.
 
     vmcore          Kernel crash dump image, generated by kdump.
 
-    trace_buffer    Output file, where binary Mero trace buffer is stored.
-    module_image    If '-m|--module-image' is used, then instead of a trace
+    output-file     Output file, where binary Mero trace buffer will be stored.
+                    If '-m|--module-image' is used, then instead of a trace
                     buffer, a m0mero.ko module image is extracted.
 
   OPTIONS:
@@ -59,6 +63,16 @@ Usage: $PROG_NAME [-h|--help] [-v|--verbose] [-f|--force] [-m|--module-image]
                     Extract m0mero.ko module image instead of a trace buffer.
                     This image is required on the next step by m0tracedump to
                     decode trace buffer.
+
+    -a|--address <addr>
+
+                    In memory address of either a trace buffer or a module image
+                    (if '-m|--module-image' is provided).
+
+    -s|--size <size>
+
+                    Size of the module image, effective only when
+                    '-m|--module-image' is provided.
 
     -v|--verbose    Print what's going on to STDERR.
 
@@ -76,8 +90,8 @@ parse_cli_options()
     # Note that we use `"$@"' to let each command-line parameter expand to a
     # separate word. The quotes around `$@' are essential!
     # We need TEMP as the `eval set --' would nuke the return value of getopt.
-    TEMP=$( getopt --options hvfm \
-                   --longoptions help,verbose,force,module-image \
+    TEMP=$( getopt --options hvfma:s: \
+                   --longoptions help,verbose,force,module-image,address:,size: \
                    --name "$PROG_NAME" -- "$@" )
 
     [[ $? -ne 0 ]] && help
@@ -91,6 +105,8 @@ parse_cli_options()
             -v|--verbose)       verbose=true; shift ;;
             -f|--force)         force=true; shift ;;
             -m|--module-image)  module_img=true; shift ;;
+            -a|--address)       address=$2; shift 2 ;;
+            -s|--size)          size=$2; shift 2 ;;
             --)                 shift; break ;;
             *)                  echo 'getopt: internal error...'; exit 1 ;;
         esac
@@ -166,6 +182,29 @@ get_value_from_crash_log()
     echo "$value"
 }
 
+get_header_address()
+{
+    readonly hdr_magic='33dec0ded502ce77'
+
+    # example output of the 'crash search <addr>' command:
+    #   ffff88007ade9000: 33dec0ded502ce77
+    #   ffffc90002fab000: 33dec0ded502ce77
+    echo 0x$(run_crash_cmd "search $hdr_magic" | cut -d: -f1 | tail -n1)
+}
+
+get_header_value_of()
+{
+    local field=$1
+
+    [[ -n $field ]] ||
+        die "trace header field can't be empty in query"
+
+    perl -MYAML::XS -e "
+        local \$/; # slurp mode ON
+        print YAML::XS::Load(<>)->{header}->{$field}
+    "
+}
+
 #
 # Main
 #
@@ -180,7 +219,7 @@ eval set -- "$cli_args"
 # sanity checks
 
 [[ -e $vmlinux ]] ||
-    die "$vmlinux file doesn't exist, please install 'kernel-debug' package!"
+    die "$vmlinux file doesn't exist, please install 'kernel-debuginfo' package!"
 
 [[ -z $1 ]] || infile=$1
 [[ -z $2 ]] || outfile=$2
@@ -191,44 +230,61 @@ if (! $force) && [[ $outfile != $stdout && -e $outfile ]] ; then
     [[ $answer =~ [yY] ]] || exit 0
 fi
 
+if $module_img && [[ -z $address && -n $size || -n $address && -z $size ]] ; then
+    die "option -m requires that -a and -s options are either omitted or both provided"
+fi
+
+#
+# dump trace header
+
+if ! $module_img || [[ -z $address ]] ; then
+    log 'finding memory location of a trace header...'
+    [[ -n $address ]] ||
+        address=$(get_header_address)
+    log "trace header address: $address"
+
+    log 'dumping trace header..'
+    end_address=$(printf 0x%x $(($address + 4 * 1024)))
+    trace_header=$(mktemp $PROG_NAME.XXXX.hdr)
+    trap "rm $trace_header" EXIT
+    run_crash_cmd "dump binary memory $trace_header $address $end_address" > /dev/null
+
+    if $module_img ; then
+        address=
+    fi
+fi
+
 if $module_img ; then
     #
     # dump m0mero.ko image
 
     log 'finding memory location of m0mero.ko core image..'
-    m0mero_core_addr=$(get_value_from_crash_log 'module core address')
-    m0mero_core_size=$(get_value_from_crash_log 'module core size')
-    log "m0mero.ko core address: $m0mero_core_addr"
-    log "m0mero.ko core size: $m0mero_core_size"
+    [[ -n $address ]] ||
+        address=$(m0tracedump -H -i $trace_header | get_header_value_of 'mod_core_addr')
+    log "m0mero.ko core address: $address"
+
+    [[ -n $size ]] ||
+        size=$(m0tracedump -H -i $trace_header | get_header_value_of 'mod_core_size')
+    log "m0mero.ko core size: $size"
 
     log 'dumping m0mero.ko core image..'
-    m0mero_core_end_addr=$(printf 0x%x $(($m0mero_core_addr + $m0mero_core_size)))
-    run_crash_cmd "dump binary memory $outfile $m0mero_core_addr $m0mero_core_end_addr" > /dev/null
+    end_address=$(printf 0x%x $(($address + $size)))
+    run_crash_cmd "dump binary memory $outfile $address $end_address" > /dev/null
     log 'done'
 else
     #
     # dump trace buffer
 
-    log 'finding memory location of a trace header...'
-    trace_hdr_addr=$(get_value_from_crash_log 'trace header address')
-    log "trace header address: $trace_hdr_addr"
-
-    log 'dumping trace header..'
-    trace_hdr_end_addr=$(printf 0x%x $(($trace_hdr_addr + 4 * 1024)))
-    trace_header=$(mktemp $PROG_NAME.XXXX.hdr)
-    trap "rm $trace_header" EXIT
-    run_crash_cmd "dump binary memory $trace_header $trace_hdr_addr $trace_hdr_end_addr" > /dev/null
-
     log 'getting actual size of header and buffer..'
-    hdr_size=$(m0tracedump -H -i $trace_header |
-               perl -ne 'print $1 if /header_size:\s+(\d+)/' )
-    buf_size=$(m0tracedump -H -i $trace_header |
-               perl -ne 'print $1 if /buffer_size:\s+(\d+)/' )
+    address=$(m0tracedump -H -i $trace_header | get_header_value_of 'header_addr')
+    hdr_size=$(m0tracedump -H -i $trace_header | get_header_value_of 'header_size')
+    buf_size=$(m0tracedump -H -i $trace_header | get_header_value_of 'buffer_size')
+    log "trace header addr (real): $address"
     log "trace header size: $hdr_size"
     log "trace buffer size: $buf_size"
 
     log 'dumping trace buffer..'
-    trace_buf_end_addr=$(printf 0x%x $(($trace_hdr_addr + $hdr_size + $buf_size)))
-    run_crash_cmd "dump binary memory $outfile $trace_hdr_addr $trace_buf_end_addr" > /dev/null
+    end_address=$(printf 0x%x $(($address + $hdr_size + $buf_size)))
+    run_crash_cmd "dump binary memory $outfile $address $end_address" > /dev/null
     log 'done'
 fi
