m0t1fs: implement fs stats collection using spiel
+ implement m0t1fs_statfs
+ allow alternative confc use in spiel
+ conf/st: Use "AD" stob type instead of "linux". This is needed for
  m0_storage_devs::sds_devices to be initialised; if the list is not
  initialised, ss_process_fom_tick() fails (to be precise,
  ss_ios_stats_ingest() does).
+ spiel: refactor struct m0_spiel to take less space on stack to fit
  statfs call into 2048 bytes frame in kernel mode.

Jira: MERO-1686

Change-Id: I400e98074dc7fc8496a9e59a65530392f900cd86

diff --git a/conf/st b/conf/st
--- a/conf/st
+++ b/conf/st
@@ -163,7 +163,7 @@ services_start() {
     local CONF_FILE=conf.xc
     local PROCESS_FID='<0x7200000000000001:1>' # process-1
     local OPTS="-P $PROFILE_FID -f $PROCESS_FID -H $HA_ENDPOINT
--m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN -F -D db -T linux -S stobs
+-m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN -F -D db -T AD -S stobs
 -A linuxstob:addb-stobs -e lnet:$IOS0_ENDPOINT -c $CONF_FILE -w 3"
 
     confdb | $M0CONFGEN >$CONF_FILE || error 'm0confgen failed'
@@ -175,14 +175,15 @@ services_start() {
     local PID=$!
     sleep 2
     kill -0 $PID 2>/dev/null ||
-	error "Failed to start m0d. See $SANDBOX_DIR/m0d.log for details."
+        error "Failed to start m0d. See $SANDBOX_DIR/m0d.log for details."
 }
 
 services_stop() { killall -q lt-m0d && wait || true; }
 
 _mount() {
-    mount -t m0t1fs -o pfid="$M0T1FS_PFID",profile="$PROFILE_FID",ha=$HA_ENDPOINT \
-	  none $SANDBOX_DIR/mnt || return $?
+    mount -t m0t1fs \
+          -o pfid="$M0T1FS_PFID",profile="$PROFILE_FID",ha=$HA_ENDPOINT \
+          none $SANDBOX_DIR/mnt || return $?
 }
 
 spiel_setup() {
