m0d: Delete fs_options_add()
* m0d: Do not obtain CLI arguments from m0_conf_filesystem::cf_params.
  This proof-of-concept functionality was only needed during nascence of
  conf module.

* conf/st: Delete defunct "autoconf" test case.
  + Don't cd to $SANDBOX_DIR explicitly -- sandbox_init does this.
  + Drop "$SANDBOX_DIR/" prefixes where possible.

Change-Id: I626a5cad8f41c08e528e1092f84efc70d7e3f232

diff --git a/conf/st b/conf/st
--- a/conf/st
+++ b/conf/st
@@ -11,8 +11,7 @@ set -eu
 ###      to be implemented.
 ###    - Add a failure test corresponding to MERO-322.
 ###    - Add a scenario that will guard against MERO-804 regressions.
-### 1. Restore "autoconf" test case.
-### 2. Start m0d via Expect wrapper.
+### 1. Start m0d via Expect wrapper.
 
 ## CAUTION: This path will be removed by superuser.
 SANDBOX_DIR=${SANDBOX_DIR:-/var/mero/sandbox.conf-st}
@@ -23,6 +22,7 @@ TRACE_CONTEXT=${M0_TRACE_PRINT_CONTEXT:-}
 
 MAX_RPC_MSG_SIZE=163840
 TM_MIN_RECV_QUEUE_LEN=2
+PROFILE_FID='<0x7000000000000001:0>' # profile-0
 
 error() { echo "$@" >&2; stop 1; }
 
@@ -30,9 +30,6 @@ M0_SRC_DIR=`readlink -f $0`
 M0_SRC_DIR=${M0_SRC_DIR%/*/*}
 
 . $M0_SRC_DIR/utils/functions # die, sandbox_init, report_and_exit
-
-## Path to the file with configuration string for confd.
-CONF_FILE=$SANDBOX_DIR/conf.txt
 
 start() {
    _init
@@ -48,12 +45,12 @@ stop() {
 _init() {
     lnet_up
     modules_insert
-    sandbox_init
-    mkdir $SANDBOX_DIR/mnt
+    sandbox_init # changes current directory to $SANDBOX_DIR
+    mkdir mnt
 }
 
 _fini() {
-    rmdir $SANDBOX_DIR/mnt
+    rmdir mnt
     sandbox_fini ${1:-}
     modules_remove
 }
@@ -90,7 +87,6 @@ export_endpoints() {
     ## the only value currently supported.
     export M0T1FS_ENDPOINT="$LNET_NID:12345:34:"
     export IOS0_ENDPOINT="$LNET_NID:12345:34:1001"
-    export IOS1_ENDPOINT="$LNET_NID:12345:34:1002"
     export HA_ENDPOINT="$IOS0_ENDPOINT"
     export MGS_ENDPOINT="$IOS0_ENDPOINT"
     export RMS_ENDPOINT="$IOS0_ENDPOINT"
@@ -106,7 +102,7 @@ lnet_up() {
 
 confdb() {
     cat <<EOF
-(root-0 verno=1 profiles=[profile-0, profile-10])
+(root-0 verno=1 profiles=[profile-0])
 (profile-0 filesystem=filesystem-0)
 (filesystem-0 rootfid=(11, 22) redundancy=2
     params=["pool_width=3", "nr_data_units=1", "nr_parity_units=1",
@@ -154,70 +150,22 @@ confdb() {
 (objv-3 real=disk-0 children=[])
 (objv-4 real=disk-1 children=[])
 (objv-5 real=disk-2 children=[])
-# --------------------
-(profile-10 filesystem=filesystem-10)
-(filesystem-10 rootfid=(33, 44) redundancy=2
-    params=["-T", "linux", "-D", "db", "-S", "stobs",
-            "-A", "linuxstob:addb-stobs", "-w", "3"]
-    mdpool=pool-10 nodes=[node-10] pools=[pool-10] racks=[])
-(node-10 memsize=16000 nr_cpu=2 last_state=3 flags=2 pool_id=pool-10
-    processes=[process-10])
-(process-10 cores=[2] mem_limit_as=0 mem_limit_rss=0 mem_limit_stack=0
-    mem_limit_memlock=0 endpoint="$IOS1_ENDPOINT" services=[service-10])
-(service-10 type=2 endpoints=["$IOS1_ENDPOINT"] sdevs=[sdev-10])
-(sdev-10 dev_idx=0 iface=4 media=2 bsize=8192 size=0 last_state=2 flags=4
-    filename="/dev/null")
-(pool-10 order=0 pvers=[])
 EOF
 }
 
-###
-### Starts Mero services.
-###
-### There are two modes of operation:
-###
-###   services_start
-###       m0d starts "confd" and several other services.
-###
-###   services_start autoconf
-###       m0d starts with minimal set of options and configures itself.
-###
 services_start() {
-    [ $# -eq 0 -o "${1:-}" = autoconf ] || error 'Invalid argument'
-    local MODE="${1:-}"
+    local CONF_FILE=conf.xc
+    local PROCESS_FID='<0x7200000000000001:1>' # process-1
+    local OPTS="-P $PROFILE_FID -f $PROCESS_FID -H $HA_ENDPOINT
+-m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN -F -D db -T linux -S stobs
+-A linuxstob:addb-stobs -e lnet:$IOS0_ENDPOINT -c $CONF_FILE -w 3"
 
-    local PROF_AC_OPT='<0x7000000000000001:0>' # "profile-0"
-    local CONFD_SPEC="-c $CONF_FILE"
-    local OPTS=
-    if [ "$MODE" = autoconf ]; then
-	OPTS="-P $PROF_AC_OPT
--e lnet:$IOS1_ENDPOINT
--m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN"
-    else
-	OPTS="
--F -D $SANDBOX_DIR/db -T linux -S $SANDBOX_DIR/stobs
--A linuxstob:$SANDBOX_DIR/addb-stobs
--e lnet:$IOS0_ENDPOINT $CONFD_SPEC
--m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN -w 3 -P $PROF_AC_OPT"
-    fi
+    confdb | $M0_SRC_DIR/utils/m0confgen >$CONF_FILE || error 'm0confgen failed'
 
-    OPTS="$OPTS -f <0x7200000000000001:1> -H $HA_ENDPOINT"
-
-    confdb | $M0_SRC_DIR/utils/m0confgen >$CONF_FILE ||
-	error 'm0confgen failed'
-
-    echo "--- `date` ---" >>$SANDBOX_DIR/m0d.log
-    cd $SANDBOX_DIR
-
-    [ "$MODE" = autoconf ] || {
-	## m0mkfs should be executed only once. It is usually executed
-	## during cluster initial setup.
-	$M0_SRC_DIR/utils/mkfs/m0mkfs $OPTS >>$SANDBOX_DIR/mkfs.log ||
-	    error 'm0mkfs failed'
-    }
+    $M0_SRC_DIR/utils/mkfs/m0mkfs $OPTS >>mkfs.log || error 'm0mkfs failed'
 
     ## XXX TODO: Start m0d via Expect wrapper. You never know how long to sleep.
-    $M0_SRC_DIR/mero/m0d $OPTS >>$SANDBOX_DIR/m0d.log 2>&1 &
+    $M0_SRC_DIR/mero/m0d $OPTS >>m0d.log 2>&1 &
     local PID=$!
     sleep 2
     kill -0 $PID 2>/dev/null ||
@@ -227,8 +175,7 @@ services_start() {
 services_stop() { killall -q lt-m0d && wait || true; }
 
 _mount() {
-    local PROF_OPT='<0x7000000000000001:0>' # "profile-0"
-    mount -t m0t1fs -o profile="$PROF_OPT",ha="$HA_ENDPOINT" \
+    mount -t m0t1fs -o profile="$PROFILE_FID",ha=$HA_ENDPOINT \
 	  none $SANDBOX_DIR/mnt || return $?
 }
 
@@ -272,12 +219,5 @@ echo 8 >/proc/sys/kernel/printk  # Print kernel messages to the console.
 say 'Test: m0t1fs'
 _mount || stop $?
 umount $SANDBOX_DIR/mnt
-
-if false; then # XXX DEBUGME
-## "conf-reqh" demo: start another instance of m0d, which configures
-## itself retrieving data from confd.
-say 'Test: reqh'
-services_start autoconf
-fi
 
 stop
