m0confgen: Let `--self-check' be run from any dir
* Delete the unit test that read conf.{cg,xc} files from ut/ directory.
  Rationale:
  - ut/conf.xc may not exist;
  - m0confgen does not always run from Mero sources directory.
* Check parsing of ut/conf.cg in scripts/st.d/05confgen.
+ Bump version to 1.6.5.

Reported-by: Dima Chumak <dmitriy.chumak@seagate.com>
Change-Id: Icd88c04bba3d945768d08d90b000ac821d527b1a

diff --git a/scripts/st.d/05confgen b/scripts/st.d/05confgen
--- a/scripts/st.d/05confgen
+++ b/scripts/st.d/05confgen
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
-set -eu
+set -eu -o pipefail
 
 cd "$M0_SRC_DIR"
-exec utils/m0confgen --self-check
+utils/m0confgen --self-check
+utils/m0confgen ut/conf.cg | utils/m0confgen -x >/dev/null || {
+    rc=$?
+    echo "m0confgen ST error: $rc" >&2
+    exit $rc
+}
