m0t1fs, m0d: make sure the most probable error paths are safe during setup
- ensure that cs_conf_setup() error paths do not cause a crash
- ensure that m0t1fs_setup() error paths do not cause a crash

Jira: MERO-1614

Change-Id: I35b9c9eeace0ce92cf844e13c66f25d174d4eaab

diff --git a/st/m0mount-fail b/st/m0mount-fail
--- a/st/m0mount-fail
+++ b/st/m0mount-fail
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-set -eu
 # set -x
-export PS4='+ [${FUNCNAME[0]:+${FUNCNAME[0]}:}${LINENO}] '
+# export PS4='+ [${FUNCNAME[0]:+${FUNCNAME[0]}:}${LINENO}] '
+set -eu
 
 ## CAUTION: This path will be removed by superuser.
 SANDBOX_DIR=${SANDBOX_DIR:-/var/mero/sandbox.m0mount-fail-st}
@@ -13,8 +13,11 @@ TRACE_CONTEXT=${M0_TRACE_PRINT_CONTEXT:-}
 MAX_RPC_MSG_SIZE=163840
 TM_MIN_RECV_QUEUE_LEN=2
 PROFILE='<0x7000000000000001:0>'        # profile-0
+PROFILE_BAD='<0x7000000000000000:999>'  # profile not existing in conf
 PROCESS_M0D='<0x7200000000000001:0>'    # process-0
 PROCESS_M0T1FS='<0x7200000000000001:4>' # process-4
+
+FINJECT=/sys/kernel/debug/mero/finject/ctl
 
 error() { echo "$@" >&2; stop 1; }
 
@@ -24,15 +27,37 @@ M0_SRC_DIR=${M0_SRC_DIR%/*/*}
 . $M0_SRC_DIR/utils/functions # die, sandbox_init, report_and_exit
 
 start() {
+    set +e
+    mount | grep debugfs > /dev/null
+    debugfs_mounted=$?
+    set -e
     _init
-    m0d_start
+
+    echo "Mount debugfs and insert m0ctl.ko so as to use fault injection"
+    if [ $debugfs_mounted -ne 0 ]; then
+	mount -t debugfs none /sys/kernel/debug
+	mount | grep debugfs
+	if [ $? -ne 0 ]
+	then
+	    echo "Failed to mount debugfs"
+	    return 1
+	fi
+    fi
+
+    echo "insmod $M0_SRC_DIR/mero/m0ctl.ko"
+    insmod $M0_SRC_DIR/mero/m0ctl.ko
+    lsmod | grep m0ctl
+    if [ $? -ne 0 ]
+    then
+	echo "Failed to insert module $M0_SRC_DIR/mero/m0ctl.ko"
+	return 1
+    fi
 }
 
 stop() {
     local rc=${1:-$?}
 
     trap - EXIT
-    m0d_stop
     _fini $rc
     report_and_exit mount-fail $rc
 }
@@ -45,6 +70,15 @@ _init() {
 }
 
 _fini() {
+    echo "rmmod $M0_SRC_DIR/mero/m0ctl.ko"
+    rmmod $M0_SRC_DIR/mero/m0ctl.ko
+    if [ $? -ne 0 ]; then
+	echo "Failed: m0ctl.ko could not be unloaded"
+	return 1
+    fi
+
+    umount /sys/kernel/debug
+
     rmdir mnt
     sandbox_fini ${1:-}
     modules_remove
@@ -91,8 +125,6 @@ export_endpoints() {
     ## the only value currently supported.
     export M0T1FS_ENDPOINT="$LNET_NID:12345:34:"
     export SERVER1_ENDPOINT="$LNET_NID:12345:34:1001"
-    export SERVER2_ENDPOINT="$LNET_NID:12345:34:1002"
-    export SPIEL_ENDPOINT="$LNET_NID:12345:34:2001"
 }
 
 ### Starts LNET. (Note that the script never stops LNET.)
@@ -156,40 +188,156 @@ conf_without_rms() {
 EOF
 }
 
-m0d_start() {
-    local CONF_FILE=conf.xc
-    local OPTS="-P $PROFILE -f $PROCESS_M0D
--m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN -F -D db -T AD -S stobs
--A linuxstob:addb-stobs -e lnet:$SERVER1_ENDPOINT -c $CONF_FILE -w 3"
+# The generated configuration does include RMS to let rconfc start normal way.
+conf_normal() {
+    cat <<EOF
+(root-0 verno=1 profiles=[profile-0])
+(profile-0 filesystem=filesystem-0)
+(filesystem-0 rootfid=(11, 22) redundancy=2
+    params=["pool_width=3", "nr_data_units=1", "nr_parity_units=1",
+            "unit_size=4096"]
+    mdpool=pool-0 nodes=[node-0] pools=[pool-0] racks=[rack-0])
+(node-0 memsize=16000 nr_cpu=2 last_state=3 flags=2 pool_id=pool-0
+    processes=[process-0])
+(process-0 cores=[3] mem_limit_as=0 mem_limit_rss=0 mem_limit_stack=0
+    mem_limit_memlock=0 endpoint="$SERVER1_ENDPOINT"
+    services=[service-1, service-2, service-3, service-4, service-5, service-6])
+(service-1 type=6 endpoints=["$SERVER1_ENDPOINT"] sdevs=[])
+(service-2 type=2 endpoints=["$SERVER1_ENDPOINT"] sdevs=[sdev-1, sdev-2, sdev-3,
+    sdev-4])
+(service-3 type=1 endpoints=["$SERVER1_ENDPOINT"] sdevs=[sdev-0])
+(service-4 type=3 endpoints=["$SERVER1_ENDPOINT"] sdevs=[])
+(service-5 type=7 endpoints=["$SERVER1_ENDPOINT"] sdevs=[])
+(service-6 type=4 endpoints=["$SERVER1_ENDPOINT"] sdevs=[])
+(pool-0 order=0 pvers=[pver-0])
+(pver-0 N=2 K=1 P=4 tolerance=[0, 0, 0, 0, 1] rackvs=[objv-0])
+(objv-0 real=rack-0 children=[objv-1])
+(objv-1 real=enclosure-0 children=[objv-2])
+(objv-2 real=controller-0 children=[objv-3, objv-4, objv-5, objv-6])
+(objv-3 real=disk-0 children=[])
+(objv-4 real=disk-1 children=[])
+(objv-5 real=disk-2 children=[])
+(objv-6 real=disk-3 children=[])
+(rack-0 encls=[enclosure-0] pvers=[pver-0])
+(enclosure-0 ctrls=[controller-0] pvers=[pver-0])
+(controller-0 node=node-0 disks=[disk-0, disk-1, disk-2, disk-3] pvers=[pver-0])
+(disk-0 dev=sdev-1 pvers=[pver-0])
+(disk-1 dev=sdev-2 pvers=[pver-0])
+(disk-2 dev=sdev-3 pvers=[pver-0])
+(disk-3 dev=sdev-4 pvers=[pver-0])
+(sdev-0 dev_idx=0 iface=4 media=1 bsize=4096 size=596000000000 last_state=3
+    flags=4 filename="/dev/sdev0")
+(sdev-1 dev_idx=0 iface=4 media=1 bsize=4096 size=596000000000 last_state=3
+    flags=4 filename="/dev/sdev1")
+(sdev-2 dev_idx=1 iface=7 media=2 bsize=8192 size=320000000000 last_state=2
+    flags=4 filename="/dev/sdev2")
+(sdev-3 dev_idx=2 iface=7 media=2 bsize=8192 size=320000000000 last_state=2
+    flags=4 filename="/dev/sdev3")
+(sdev-4 dev_idx=3 iface=7 media=2 bsize=8192 size=320000000000 last_state=2
+    flags=4 filename="/dev/sdev4")
+EOF
+}
 
-    conf_without_rms | $M0_SRC_DIR/utils/m0confgen >$CONF_FILE ||
+m0d_start() {
+    local conf_generator=$1
+    local conf_file=conf.xc
+    local opts="-P $PROFILE -f $PROCESS_M0D
+-m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN -F -D db -T AD -S stobs
+-A linuxstob:addb-stobs -e lnet:$SERVER1_ENDPOINT -c $conf_file -w 3"
+
+    $conf_generator | $M0_SRC_DIR/utils/m0confgen >$conf_file ||
         error 'm0confgen failed'
 
-    $M0_SRC_DIR/utils/mkfs/m0mkfs $OPTS &>mkfs.log || error 'm0mkfs failed'
+    $M0_SRC_DIR/utils/mkfs/m0mkfs $opts &>mkfs.log || error 'm0mkfs failed'
 
-    echo $M0_SRC_DIR/mero/m0d $OPTS >m0d.log
-    $M0_SRC_DIR/mero/m0d $OPTS &>>m0d.log &
-    local PID=$!
+    echo $M0_SRC_DIR/mero/m0d $opts >m0d.log
+    $M0_SRC_DIR/mero/m0d $opts &>>m0d.log &
+    local pid=$!
     sleep 2
-    kill -0 $PID 2>/dev/null ||
+    kill -0 $pid 2>/dev/null ||
         error "Failed to start m0d. See $SANDBOX_DIR/m0d.log for details."
 }
 
 m0d_stop() { killall -q lt-m0d && wait || true; }
 
 mount_fail() {
-    local OPTS='-t m0t1fs'
-    OPTS+=" -o pfid=$PROCESS_M0T1FS,profile=$PROFILE,ha=$SERVER1_ENDPOINT"
-    OPTS+=" none $SANDBOX_DIR/mnt"
+    local profile=$1
+    local opts='-t m0t1fs'
+    opts+=" -o pfid=$PROCESS_M0T1FS,profile=$profile,ha=$SERVER1_ENDPOINT"
+    opts+=" none $SANDBOX_DIR/mnt"
 
-    echo mount $OPTS >mount.log
-    if mount $OPTS &>>mount.log; then
+    echo mount $opts >mount.log
+    if mount $opts &>>mount.log; then
         echo 'mount failed to fail' | tee -a mount.log >&2
         umount $SANDBOX_DIR/mnt
         return 1
     else
         echo "mount failed as expected" &>>mount.log
     fi
+}
+
+## -------------------------------------------------------------------
+## test suite data
+## -------------------------------------------------------------------
+
+TEST_CASES=(
+    [0]="no RMS in conf"
+    [1]="a profile not in conf"
+    [2]="m0_pools_common_init() to fail"
+    [3]="m0_pools_setup() to fail"
+    [4]="m0_pools_service_ctx_create() to fail"
+    [5]="m0_pool_versions_setup() to fail"
+    [6]="m0_flset_build() to fail"
+    [7]="m0_pool_version_get() to fail"
+    [8]="m0t1fs_reqh_services_start() to fail"
+)
+
+FINJECT_WHERE=(
+    [2]='m0_conf_ios_devices_count'
+    [3]='m0_pools_setup'
+    [4]='service_ctxs_create'
+    [5]='m0_pool_versions_setup'
+    [6]='flset_diter_init'
+    [7]='m0_conf_pver_get'
+    [8]='m0_conf_process2service_get'
+)
+
+# no entry implies conf_normal
+CONF_GENERATOR=(
+    [0]=conf_without_rms
+)
+
+# no entry implies $PROFILE
+CONF_PROFILE=(
+    [1]=$PROFILE_BAD
+)
+
+# no need to restart m0d while running conf_normal
+M0D_START=( [0]=1 [1]=1 )
+M0D_STOP=(  [0]=1 [8]=1 )
+
+run_test() {
+    local conf_generator=${CONF_GENERATOR[$1]:-conf_normal}
+    local conf_profile=${CONF_PROFILE[$1]:-$PROFILE}
+    local fi_where=${FINJECT_WHERE[$1]:-''}
+    local verbose=${MF_VERBOSE:-0} # 0 - mute; 1 - title only; 2 - detailed
+    local m0d_start=${M0D_START[$1]:-0}
+    local m0d_stop=${M0D_STOP[$1]:-0}
+
+    if [ $verbose -ne 0 ]; then
+	local title="$idx > mounting with ${TEST_CASES[$1]}..."
+	[ $verbose -lt 2 ] || title+=" generator=$conf_generator, profile=$conf_profile"
+	echo $title
+    fi
+    [ $m0d_start -eq 0 ] || m0d_start $conf_generator
+    if [ -n "$fi_where" ]; then
+	fi_command="enable $fi_where diter_fail oneshot"
+	echo $fi_command > $FINJECT
+	[ $verbose -lt 2 ] || echo $fi_command
+    fi
+    mount_fail $conf_profile
+    [ $m0d_stop -eq 0 ] || m0d_stop
+    [ $verbose -lt 2 ] || echo "  < OK, mount failed"
 }
 
 ## -------------------------------------------------------------------
@@ -202,6 +350,10 @@ trap stop EXIT
 start
 
 echo 8 >/proc/sys/kernel/printk  # Print kernel messages to the console.
-mount_fail
+
+for (( idx = 0; idx < ${#TEST_CASES[*]}; idx++ ))
+do
+    run_test $idx
+done
 
 stop
