st: fix initscripts test
* decrease unit size to 1MiB and write block size to 4MiB
* properly check exit code of `dd` process.

Change-Id: Ia326bd4cd6041d67ff9999fa34d885c5b0feba18

diff --git a/st/m0t1fs b/st/m0t1fs
--- a/st/m0t1fs
+++ b/st/m0t1fs
@@ -4,6 +4,8 @@
 # m0t1fs system test
 #
 
+# exit immediately if one the commands exits with a non-zero status
+set -e -o pipefail
 
 #
 # Global vars
@@ -154,8 +156,8 @@ do_m0t1fs_system_test()
     local test_file_path='/mnt/m0t1fs/0:4200000'
 
     touch $test_file_path
-    # set unit_size to 16MB (see layout/layout_pver.c:m0_lid_to_unit_map)
-    setfattr -n lid -v 13 $test_file_path
+    # set unit_size to 1MB (see layout/layout_pver.c:m0_lid_to_unit_map)
+    setfattr -n lid -v 9 $test_file_path
 
     local src_file_path=/dev/zero
 
@@ -167,12 +169,10 @@ do_m0t1fs_system_test()
     done
 
     debug "using $device as a source file"
-    dd if=$src_file_path of=$test_file_path bs=32M &
-
+    dd if=$src_file_path of=$test_file_path bs=4M count=240 &
     local dd_pid=$!
-    local i=60
 
-    while [[ $((--i)) -gt 0 ]] ; do
+    while true ; do
         sleep 1
         if ps -p $dd_pid &> /dev/null ; then
             kill -USR1 $dd_pid
@@ -181,8 +181,10 @@ do_m0t1fs_system_test()
         fi
     done
 
-    debug "do_m0t1fs_system_test: stop dd"
-    kill $dd_pid || true
+    wait $dd_pid
+    rc=$?
+    [[ $rc -eq 0 ]] ||
+        die "dd command finished with error code $rc"
 
     debug "do_m0t1fs_system_test: sleep 30 sec"
     sleep 10 # FIXME: w/a for 'umount: /mnt/m0t1fs: device is busy'
@@ -216,9 +218,6 @@ trap cleanup EXIT
 # Main
 #
 
-# exit immediately if one the commands exits with a non-zero status
-set -e
-
 parse_cli_options "$@"
 
 if ! is_mero_installed && [[ -z $rpm_pkg ]] ; then
@@ -234,7 +233,7 @@ fi
 info 'Running m0setup cleanup'
 m0setup -c
 
-for ios_num in 1 2 ; do
+for ios_num in 1 ; do
     info "--------------- m0t1fs test with $ios_num ioservice(s)  ---------------"
 
     info '/var/mero cleanup'
