Add Process reconfig functionality:
Add restart functionality to m0d
- signal to m0d
- flag reconfig to mero instance
- handle singnal with select reconfig/stop
- restart functionality to m0d

Fix stop session when service is died by reconfig

Add clean data for lockers fini
Add clean ldata for locality fini
Add clean locality data for addb2 fini
Add fini addb2 ctx, fop ctx, fop type, confx,
Add quiesce stage init/fini modules

Add reqh lockers free

Change Process configure cores field as m0_bitmap for Conf & Spiel interface

Update sss/st system test - add Process reconfig test

Change-Id: I45636b3d72b5886cc5859fe6e08058a513a56715

diff --git a/sss/st b/sss/st
--- a/sss/st
+++ b/sss/st
@@ -9,13 +9,14 @@ umask 0002
 ## CAUTION: This path will be removed by superuser.
 SANDBOX_DIR=${SANDBOX_DIR:-/var/mero/sandbox.sss-st}
 
-SERVER_TMID=1001
+SERVER_TMID=1
 CLIENT_TMID=1002
 SVC_IOS_FID='<7300000000000001:1>'
 CONFD_FID='<7300000000000001:2>'
 SVC_IOS_ID='(8286623314361712641, 1)'
 SVC_ID_NOENT='(8286623314361712641, 10)'
 SVC_ID=$SVC_IOS_ID
+PROC_ID='(0x7200000000000001, 5)'
 
 M0_CORE_DIR=`readlink -f $0`
 M0_CORE_DIR=${M0_CORE_DIR%/*/*}
@@ -52,6 +53,26 @@ sss_send() {
 		-d "($CMD, \"$SVC\", $ID, \"${SS_PARAM:-}\")" -v
 }
 
+sss_process_send() {
+	[ $# -eq 2 ] || die 'Invalid arguments'
+	local CMD=
+	case "$1" in  # see m0_ss_process_req_cmd for the values
+		M0_PROCESS_STOP) CMD=0;;
+		M0_PROCESS_RECONFIG) CMD=1;;
+		M0_PROCESS_HEALTH) CMD=2;;
+		M0_PROCESS_QUIESCE) CMD=3;;
+		M0_PROCESS_RUNNING_LIST) CMD=4;;
+		*) die 'Invalid value';;
+	esac
+	local ID="$2"
+
+	env ${TRACE_console:-} timeout 60 $M0_CORE_DIR/console/bin/m0console \
+		-f $(opcode M0_SSS_PROCESS_REQ_OPCODE) \
+		-s $(endpoint $SERVER_TMID) -c $(endpoint $CLIENT_TMID) \
+		-d "($CMD, $ID)" -v || true
+
+}
+
 svc_state() {
 	case "${1:-}" in  # see m0_reqh_service_state for the values
 		M0_RST_INITIALISED) echo 1;;
@@ -62,6 +83,7 @@ svc_state() {
 		_EINVAL)   echo -22;;
 		_EPROTO)   echo -71;;
 		_EALREADY) echo -114;;
+		OK) echo 0;;
 		*) die 'Invalid value';;
 	esac
 }
@@ -81,6 +103,28 @@ sss_check() {
 	[ "$ACTUAL" = "$EXPECTED" ] || \
 		die "Expected service state (${EXPECTED}) != actual (${ACTUAL})"
 	echo 'OK' >&2
+}
+
+sss_process_check() {
+	[ $# -eq 4 ] || die 'Invalid arguments'
+	local COMMAND="$1"
+	local PROCESS_ID="$2"
+	local KEY_NAME="$3"
+	local EXPECTED_VALUE="$4"
+
+	echo -n "$COMMAND $PROCESS_ID... " >&2
+	sss_process_send $COMMAND "$PROCESS_ID" &>$SANDBOX_DIR/console.log
+	local ACTUAL=$(awk "/$KEY_NAME/ {print \$3}" $SANDBOX_DIR/console.log)
+	local EXPECTED=$(svc_state $EXPECTED_VALUE)
+	[ "$ACTUAL" = "$EXPECTED" ] || \
+		die "Expected service state (${EXPECTED}) != actual (${ACTUAL})"
+	echo 'OK' >&2
+}
+
+sss_process_restart_check() {
+	local EXPECTED=$(grep Restarting $SANDBOX_DIR/m0d.log)
+	[ A"$EXPECTED" = A"Restarting" ] || die "Expected restarting state"
+	echo 'Restart OK' >&2
 }
 
 sandbox_init() {
@@ -155,6 +199,11 @@ esac
 $M0_CORE_DIR/conf/st insmod
 sandbox_init
 m0d_start
+
+sss_process_check M0_PROCESS_RECONFIG "$PROC_ID" sspr_rc OK
+# wait reconfigure
+sleep 5
+sss_process_restart_check
 
 sss_check ioservice M0_SERVICE_STATUS "$SVC_ID" ssr_state M0_RST_STARTED
 sss_check ioservice M0_SERVICE_STATUS "$SVC_ID_NOENT" ssr_rc _ENOENT  # invalid id
