MERO-1239: sss ST failure: Expected service state (0) != actual ()
Service get FOP before started completely.
Possibly other problem, but script non show it.

* Add print additional information: if expected replay FOP not received then
  show return code console application
* Increase timeout

Change-Id: I8ed2bd35c787836bfdde7c815cb1217dd792b776

diff --git a/sss/st b/sss/st
--- a/sss/st
+++ b/sss/st
@@ -48,6 +48,8 @@ sss_send() {
 		-f $(opcode M0_SSS_REQ_OPCODE) \
 		-s $(endpoint $SERVER_TMID) -c $(endpoint $CLIENT_TMID) \
 		-d "($CMD, \"$SVC\", $ID, \"${SS_PARAM:-}\")" -v
+	echo rc_send = $? >&2
+
 }
 
 sss_process_send() {
@@ -63,11 +65,15 @@ sss_process_send() {
 	esac
 	local ID="$2"
 
-	env ${TRACE_console:-} timeout 60 $M0_CORE_DIR/console/bin/m0console \
+	# timeout was increase to 90 sec by tiket MERO-1239
+	# if bug MERO-1239 will be reproduce then need research
+	# $SANDBOX_DIR/console.log for additional information
+	#
+	env ${TRACE_console:-} timeout 90 $M0_CORE_DIR/console/bin/m0console \
 		-f $(opcode M0_SSS_PROCESS_REQ_OPCODE) \
 		-s $(endpoint $SERVER_TMID) -c $(endpoint $CLIENT_TMID) \
 		-d "($CMD, $ID)" -v || true
-
+	echo rc_send = $? >&2
 }
 
 svc_state() {
@@ -97,6 +103,8 @@ sss_check() {
 	sss_send $SERVICE_NAME $COMMAND "$SERVICE_ID" &>$SANDBOX_DIR/console.log
 	local ACTUAL=$(awk "/$KEY_NAME/ {print \$3}" $SANDBOX_DIR/console.log)
 	local EXPECTED=$(svc_state $EXPECTED_VALUE)
+	[ A"$ACTUAL" != A ] || die "Generic error = " \
+			$(awk "/rc_send/ {print \$3}" $SANDBOX_DIR/console.log)
 	[ "$ACTUAL" = "$EXPECTED" ] || \
 		die "Expected service state (${EXPECTED}) != actual (${ACTUAL})"
 	echo 'OK' >&2
@@ -113,6 +121,8 @@ sss_process_check() {
 	sss_process_send $COMMAND "$PROCESS_ID" &>$SANDBOX_DIR/console.log
 	local ACTUAL=$(awk "/$KEY_NAME/ {print \$3}" $SANDBOX_DIR/console.log)
 	local EXPECTED=$(svc_state $EXPECTED_VALUE)
+	[ A"$ACTUAL" != A ] || die "Generic error = " \
+			$(awk "/rc_send/ {print \$3}" $SANDBOX_DIR/console.log)
 	[ "$ACTUAL" = "$EXPECTED" ] || \
 		die "Expected service state (${EXPECTED}) != actual (${ACTUAL})"
 	echo 'OK' >&2
