reqh: Register services using M0_CST_* names
- sss/st: use symbolic fid format;
- conf/helpers: delete m0_conf_service_name_dup(),
  we can do just fine without this interface;
- conf/helpers: remove service_name,
  m0_conf_service_type2str() should be used instead;
- conf: s/M0_CST_STS/M0_CST_STATS/,
  there is no need to be obscure.

Change-Id: I9050b4ece5fcb6421a002f17265dc498b2b44ded

diff --git a/sss/st b/sss/st
--- a/sss/st
+++ b/sss/st
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 set -eu
+# set -x
+export PS4='+ ${FUNCNAME[0]:+${FUNCNAME[0]}():}line ${LINENO}: '
+
 umask 0002
 
 # TRACE_m0d='M0_TRACE_IMMEDIATE_MASK=!memory,stob M0_TRACE_LEVEL=info+'
@@ -10,9 +13,9 @@ SANDBOX_DIR=${SANDBOX_DIR:-/var/mero/sandbox.sss-st}
 
 SERVER_TMID=1
 CLIENT_TMID=1002
-SVC_IOS_ID='(0x7300000000000001, 0)'
-SVC_ID_NOENT='(0x7300000000000001, 10)'
-SVC_ID=$SVC_IOS_ID
+SVC_IOS_ID='^s|1:0'
+SVC_ID_NOENT='^s|1:99'
+SVC_ID="$SVC_IOS_ID"
 PROC_ID='^r|1:5'
 
 M0_SRC_DIR=`readlink -f $0`
@@ -35,9 +38,9 @@ sss_send() {
 			if [ $SVC = confd -a -z "${CONFDB_m0d:-}" ]; then
 				local SS_PARAM="$CONFDB_PATH"
 			fi;;
-		M0_SERVICE_START)  CMD=0;;
-		M0_SERVICE_STOP)   CMD=1;;
-		M0_SERVICE_STATUS) CMD=2;;
+		M0_SERVICE_START)   CMD=0;;
+		M0_SERVICE_STOP)    CMD=1;;
+		M0_SERVICE_STATUS)  CMD=2;;
 		M0_SERVICE_QUIESCE) CMD=3;;
 		*) die 'Invalid value';;
 	esac
@@ -99,18 +102,23 @@ sss_check() {
 	local KEY_NAME="$4"
 	local EXPECTED_VALUE="$5"
 
+	if [ "${SERVICE_NAME#M0_CST_}" = "$SERVICE_NAME" ]; then
+		[ "$SERVICE_NAME" = 'unknown' ] ||
+			die "Invalid service name: $SERVICE_NAME"
+	fi
+
 	echo -n "$SERVICE_NAME $COMMAND $SERVICE_ID.. " >&2
 	sss_send $SERVICE_NAME $COMMAND "$SERVICE_ID" &>$SANDBOX_DIR/console.log
 	local ACTUAL=$(awk "/$KEY_NAME/ {print \$3}" $SANDBOX_DIR/console.log)
 	local EXPECTED=$(svc_state $EXPECTED_VALUE)
-	[ A"$ACTUAL" != A ] || die "Generic error = " \
+	[ -n "$ACTUAL" ] || die "Generic error = " \
 			$(awk "/rc_send/ {print \$3}" $SANDBOX_DIR/console.log)
 	[ "$ACTUAL" = "$EXPECTED" ] || \
 		die "Expected service state (${EXPECTED}) != actual (${ACTUAL})"
 	echo 'OK' >&2
 }
 
-sss_process_check() {
+sss_process_check() {  # XXX FIXME: code duplication
 	[ $# -eq 5 ] || die 'Invalid arguments'
 	local COMMAND="$1"
 	local PROCESS_ID="$2"
@@ -123,7 +131,7 @@ sss_process_check() {
 	    &>$SANDBOX_DIR/console.log
 	local ACTUAL=$(awk "/$KEY_NAME/ {print \$3}" $SANDBOX_DIR/console.log)
 	local EXPECTED=$(svc_state $EXPECTED_VALUE)
-	[ A"$ACTUAL" != A ] || die "Generic error = " \
+	[ -n "$ACTUAL" ] || die "Generic error = " \
 			$(awk "/rc_send/ {print \$3}" $SANDBOX_DIR/console.log)
 	[ "$ACTUAL" = "$EXPECTED" ] || \
 		die "Expected service state (${EXPECTED}) != actual (${ACTUAL})"
@@ -132,7 +140,7 @@ sss_process_check() {
 
 sss_process_restart_check() {
 	local EXPECTED=$(grep Restarting $SANDBOX_DIR/m0d.log)
-	[ A"$EXPECTED" = A"Restarting" ] || die "Expected restarting state"
+	[ "$EXPECTED" = 'Restarting' ] || die "Expected restarting state"
 	echo 'Restart OK' >&2
 }
 
@@ -158,13 +166,14 @@ m0d_start() {
 		die 'm0mkfs failed'
 	echo 'OK' >&2
 
-	## "sns_repair" and "sns_rebalance" (see below)
-	## require "ioservice" running.
+	## M0_CST_SNS_REP and M0_CST_SNS_REB (see below)
+	## require M0_CST_IOS running.
 	env ${TRACE_m0d:-} $M0_SRC_DIR/mero/m0d $MKFS_OPTS \
 		${CONFDB_m0d:-} $M0D_OPT -f '<0x7200000000000001:5>' \
 		&>$SANDBOX_DIR/m0d.log &
 	sleep 1
-	sss_check ioservice M0_SERVICE_STATUS "$SVC_ID" ssr_state M0_RST_STARTED
+	sss_check M0_CST_IOS M0_SERVICE_STATUS "$SVC_ID" ssr_state \
+		M0_RST_STARTED
 	killall -q -0 lt-m0d || die 'Failed to start m0d'
 }
 
@@ -209,25 +218,24 @@ sss_process_restart_check
 sss_process_check M0_PROCESS_LIB_LOAD "$PROC_ID" '"/lib64/libc.so.6 "' sspr_rc OK
 sss_process_check M0_PROCESS_LIB_LOAD "$PROC_ID" '"bah.so "' sspr_rc _EINVAL
 
-sss_check ioservice M0_SERVICE_STATUS "$SVC_ID" ssr_state M0_RST_STARTED
-sss_check ioservice M0_SERVICE_STATUS "$SVC_ID_NOENT" ssr_rc _ENOENT  # invalid id
+sss_check M0_CST_IOS M0_SERVICE_STATUS "$SVC_ID" ssr_state M0_RST_STARTED
+sss_check M0_CST_IOS M0_SERVICE_STATUS "$SVC_ID_NOENT" ssr_rc _ENOENT
 
-#@todo ioservice restart is not working
-# Check after MERO-1172 is fixed.
-#SVC_NAMES=(ioservice mdservice rmservice sns_repair sns_rebalance addb2 )
-SVC_NAMES=(mdservice rmservice sns_repair sns_rebalance addb2 )
+# XXX FIXME: M0_CST_IOS restart is not working; see MERO-1172.
+SVC_NAMES=(#M0_CST_IOS
+           M0_CST_MDS M0_CST_RMS M0_CST_SNS_REP M0_CST_SNS_REB M0_CST_ADDB2)
 for ((i=0; i < ${#SVC_NAMES[*]}; i++)); do
-	SVC_ID="(0x7300000000000001, $((i+1)))"
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS  "$SVC_ID" \
+	SVC_ID="^s|1:$((i+1))"
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS "$SVC_ID" \
 		ssr_state M0_RST_STARTED
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_QUIESCE  "$SVC_ID" \
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_QUIESCE "$SVC_ID" \
 		ssr_state M0_RST_STOPPING
 	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STOP "$SVC_ID" \
 		ssr_state M0_RST_STOPPED
 done
 
 for ((i=0; i < ${#SVC_NAMES[*]}; i++)); do
-	SVC_ID="(0x7300000000000001, $((i+1)))"
+	SVC_ID="^s|1:$((i+1))"
 	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS  "$SVC_ID" \
 		ssr_rc _ENOENT
 	sss_check ${SVC_NAMES[$i]} M0_SERVICE_INIT    "$SVC_ID" \
@@ -250,28 +258,28 @@ for ((i=0; i < ${#SVC_NAMES[*]}; i++)); do
 		ssr_rc _ENOENT
 done
 for ((i=0; i < ${#SVC_NAMES[*]}; i++)); do
-        SVC_ID="(0x7300000000000001, $((i+1)))"
-        sss_check ${SVC_NAMES[$i]} M0_SERVICE_INIT    "$SVC_ID" \
-                ssr_state M0_RST_INITIALISED
-        sss_check ${SVC_NAMES[$i]} M0_SERVICE_START "$SVC_ID" \
-                ssr_state M0_RST_STARTED
-        sss_check ${SVC_NAMES[$i]} M0_SERVICE_QUIESCE  "$SVC_ID" \
-                ssr_state M0_RST_STOPPING
-        sss_check ${SVC_NAMES[$i]} M0_SERVICE_STOP  "$SVC_ID" \
-                ssr_state M0_RST_STOPPED
+	SVC_ID="^s|1:$((i+1))"
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_INIT    "$SVC_ID" \
+		ssr_state M0_RST_INITIALISED
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_START   "$SVC_ID" \
+		ssr_state M0_RST_STARTED
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_QUIESCE "$SVC_ID" \
+		ssr_state M0_RST_STOPPING
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STOP    "$SVC_ID" \
+		ssr_state M0_RST_STOPPED
 done
 
 SVC_ID=$SVC_IOS_ID
 
-sss_check invalid M0_SERVICE_START "$SVC_ID_NOENT" ssr_rc _ENOENT
-sss_check invalid M0_SERVICE_START "$SVC_ID"       ssr_rc _EPROTO
+sss_check unknown M0_SERVICE_START "$SVC_ID_NOENT" ssr_rc _ENOENT
+sss_check unknown M0_SERVICE_START "$SVC_ID"       ssr_rc _EPROTO
 
-sss_check ioservice M0_SERVICE_QUIESCE "$SVC_ID" ssr_state M0_RST_STOPPING
-sss_check ioservice M0_SERVICE_STATUS  "$SVC_ID" ssr_state M0_RST_STOPPING
-sss_check ioservice M0_SERVICE_STOP    "$SVC_ID" ssr_state M0_RST_STOPPED
-sss_check ioservice M0_SERVICE_STATUS  "$SVC_ID" ssr_rc    _ENOENT
-sss_check ioservice M0_SERVICE_INIT    "$SVC_ID" ssr_state M0_RST_INITIALISED
-sss_check ioservice M0_SERVICE_START   "$SVC_ID" ssr_state M0_RST_STARTED
+sss_check M0_CST_IOS M0_SERVICE_QUIESCE "$SVC_ID" ssr_state M0_RST_STOPPING
+sss_check M0_CST_IOS M0_SERVICE_STATUS  "$SVC_ID" ssr_state M0_RST_STOPPING
+sss_check M0_CST_IOS M0_SERVICE_STOP    "$SVC_ID" ssr_state M0_RST_STOPPED
+sss_check M0_CST_IOS M0_SERVICE_STATUS  "$SVC_ID" ssr_rc    _ENOENT
+sss_check M0_CST_IOS M0_SERVICE_INIT    "$SVC_ID" ssr_state M0_RST_INITIALISED
+sss_check M0_CST_IOS M0_SERVICE_START   "$SVC_ID" ssr_state M0_RST_STARTED
 
 m0d_stop
 sandbox_fini
