Mero-405: sss/st:expected error should be checked from m0_sss_rep::ssr_rc
Change-Id: I3b796b872df092dae72544b1a5591b7fdb9e1713

diff --git a/sss/st b/sss/st
--- a/sss/st
+++ b/sss/st
@@ -56,16 +56,17 @@ svc_state() {
 }
 
 sss_check() {
-	[ $# -eq 4 ] || die 'Invalid arguments'
+	[ $# -eq 5 ] || die 'Invalid arguments'
 	local SERVICE_NAME="$1"
 	local COMMAND="$2"
 	local SERVICE_ID="$3"
-	local EXPECTED_STATE="$4"
+	local KEY_NAME="$4"
+	local EXPECTED_VALUE="$5"
 
 	echo -n "$SERVICE_NAME $COMMAND... " >&2
 	sss_send $SERVICE_NAME $COMMAND "$SERVICE_ID" &>$SANDBOX_DIR/console.log
-	local ACTUAL=$(awk "/ssr_status/ {print \$3}" $SANDBOX_DIR/console.log)
-	local EXPECTED=$(svc_state $EXPECTED_STATE)
+	local ACTUAL=$(awk "/$KEY_NAME/ {print \$3}" $SANDBOX_DIR/console.log)
+	local EXPECTED=$(svc_state $EXPECTED_VALUE)
 	[ "$ACTUAL" = "$EXPECTED" ] || \
 		die "Expected service state (${EXPECTED}) != actual (${ACTUAL})"
 	echo 'OK' >&2
@@ -142,21 +143,27 @@ $M0_CORE_DIR/m0t1fs/linux_kernel/st/st insmod
 sandbox_init
 m0d_start
 
-sss_check ioservice M0_SERVICE_STATUS "$SVC_ID" M0_RST_STARTED
-sss_check ioservice M0_SERVICE_STATUS '(0, 0)'  _ENOENT  # invalid id
+sss_check ioservice M0_SERVICE_STATUS "$SVC_ID" ssr_status M0_RST_STARTED
+sss_check ioservice M0_SERVICE_STATUS '(0, 0)'  ssr_rc     _ENOENT  # invalid id
 
 SVC_NAMES=(confd stats rmservice mdservice addb sns_repair sns_rebalance)
 for ((i=0; i < ${#SVC_NAMES[*]}; i += 1)); do
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS "$SVC_ID" M0_RST_STOPPED
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_START  "$SVC_ID" M0_RST_STARTED
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS "$SVC_ID" M0_RST_STARTED
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_START  "$SVC_ID" _EALREADY
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STOP   "$SVC_ID" M0_RST_STOPPED
-	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS "$SVC_ID" M0_RST_STOPPED
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS "$SVC_ID" \
+		ssr_status M0_RST_STOPPED
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_START  "$SVC_ID" \
+		ssr_status M0_RST_STARTED
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS "$SVC_ID" \
+		ssr_status M0_RST_STARTED
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_START  "$SVC_ID" \
+		ssr_rc     _EALREADY
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STOP   "$SVC_ID" \
+		ssr_status M0_RST_STOPPED
+	sss_check ${SVC_NAMES[$i]} M0_SERVICE_STATUS "$SVC_ID" \
+		ssr_status M0_RST_STOPPED
 done
-sss_check unknown_service M0_SERVICE_START  "$SVC_ID" _ENOENT
-sss_check ioservice       M0_SERVICE_STOP   "$SVC_ID" M0_RST_STOPPED
-sss_check ioservice       M0_SERVICE_STATUS "$SVC_ID" M0_RST_STOPPED
+sss_check unknown_service M0_SERVICE_START  "$SVC_ID" ssr_rc     _ENOENT
+sss_check ioservice       M0_SERVICE_STOP   "$SVC_ID" ssr_status M0_RST_STOPPED
+sss_check ioservice       M0_SERVICE_STATUS "$SVC_ID" ssr_status M0_RST_STOPPED
 
 m0d_stop
 sandbox_fini
