utils/functions: add m0_modules_insert/remove
Change-Id: I8a72288038d255ab205c422179e384ff26d28ab4

diff --git a/utils/functions b/utils/functions
--- a/utils/functions
+++ b/utils/functions
@@ -56,3 +56,48 @@ opcode() {
     grep -v '#pragma once' $M0_SRC_DIR/rpc/rpc_opcodes.h | cpp |
         awk "/$NAME/ {print \$3}" | tr -d ,
 }
+
+m0_modules_insert() {
+    insmod $M0_SRC_DIR/extra-libs/gf-complete/src/linux_kernel/m0gf.ko ||
+        die 'Inserting m0gf.ko failed'
+
+    insmod $M0_SRC_DIR/mero/m0mero.ko \
+    local_addr=$M0T1FS_ENDPOINT \
+    max_rpc_msg_size=$MAX_RPC_MSG_SIZE \
+    tm_recv_queue_min_len=$TM_MIN_RECV_QUEUE_LEN \
+    ${M0_TRACE_IMMEDIATE_MASK:+trace_immediate_mask=$M0_TRACE_IMMEDIATE_MASK} \
+    ${M0_TRACE_LEVEL:+trace_level=$M0_TRACE_LEVEL} \
+    ${M0_TRACE_PRINT_CONTEXT:+trace_print_context=$M0_TRACE_PRINT_CONTEXT} \
+    || {
+        rmmod m0gf
+        die 'Inserting m0mero.ko failed'
+    }
+    insmod $M0_SRC_DIR/mero/m0ctl.ko || {
+        rmmod m0mero
+        rmmod m0gf
+        die 'inserting m0ctl failed'
+    }
+}
+
+m0_modules_remove() {
+    rmmod m0ctl || true
+    rmmod m0mero || true
+    rmmod m0gf || true
+}
+
+lnet_up() {
+    modprobe lnet
+    lctl network up >/dev/null
+    local LNET_NID=`lctl list_nids | head -1`
+
+    ## LNet endpoint address format (see net/lnet/lnet.h):
+    ##     NID:PID:Portal:TMID
+    ##
+    ## The PID value of 12345 is used by Lustre in the kernel and is
+    ## the only value currently supported.
+    export M0T1FS_ENDPOINT="$LNET_NID:12345:34:"
+    export M0D1_ENDPOINT="$LNET_NID:12345:34:1001"
+    export M0D2_ENDPOINT="$LNET_NID:12345:34:1002"
+    export M0D3_ENDPOINT="$LNET_NID:12345:34:1003"
+    export SPIEL_ENDPOINT="$LNET_NID:12345:34:2001"
+}
