utils/functions (sandbox_fini): Add optional parameter
Preserve $SANDBOX_DIR if sandbox_fini is called with non-zero argument.
(Another - old - way to preserve $SANDBOX_DIR is to set `KEEP_SANDBOX'
environment variable.)

+ conf/st: Don't delete $SANDBOX_DIR if testing fails.

Change-Id: Ic6ca53a1e347b13401eba4f58cd9409dc5b74bee

diff --git a/utils/functions b/utils/functions
--- a/utils/functions
+++ b/utils/functions
@@ -11,8 +11,12 @@ sandbox_init() {
 
 sandbox_fini() {
     [ -n "${SANDBOX_DIR:-}" ] || die 'SANDBOX_DIR: unbound variable'
-    popd >/dev/null
-    [ -n "${KEEP_SANDBOX:-}" ] || rm -r $SANDBOX_DIR
+    local rc=${1:-0} # non-zero value denotes unsuccessful termination
+
+    popd &>/dev/null || true
+    if [ -z "${KEEP_SANDBOX:-}" -a $rc -eq 0 ]; then
+        rm -r $SANDBOX_DIR
+    fi
 }
 
 report_and_exit() {
