m0reportbug (misc_files): Don't fail if some file is missing
`/var/mero/confd/conf.xc', referred to by MERO_CONF_XC variable, is not
guaranteed to exist.

+ Bump version to 0.13.2.

Change-Id: I41cc07604a070df562926a84abfa9ba2a31968cc

diff --git a/utils/m0reportbug b/utils/m0reportbug
--- a/utils/m0reportbug
+++ b/utils/m0reportbug
@@ -3,12 +3,16 @@ set -eu
 # set -x
 export PS4='+ [${FUNCNAME[0]:+${FUNCNAME[0]}:}${LINENO}] '
 
-VERSION=0.13.1
+VERSION=0.13.2
 ###
 ### History:
 ###
 ### Date       Version Description
 ### ---------- ------- ----------------------------------------------------
+### 2016-03-29 0.13.2  misc_files(): Don't fail if some file is missing.
+###                    `/var/mero/confd/conf.xc', referred to by
+###                    MERO_CONF_XC variable, is not guaranteed to exist.
+###
 ### 2016-03-03 0.13.1  Add `lt-m0rwlock' to _path_src().
 ###
 ### 2016-03-01 0.13    * m0traces(): Collect at least two trace files from
@@ -208,6 +212,10 @@ misc_files() {
     } | while read path; do
         [ "$path" != "${path#/}" ] || {
             warn "${FUNCNAME[0]}: Absolute path expected: $path"
+            continue
+        }
+        [ -f $path ] || {
+            echo "$path: No such file"
             continue
         }
         mkdir -p $outdir$(dirname $path)
