m0reportbug: Update MERO_PACKAGE_VERSION; fix bugs
m0reportbug failed on devvm due to Mero package version mismatch.
The script also wasn't able to collect libmero.so.* and lt-m0ut files.
And gdb backtraces were missing. Oh dear.
These issues are fixed now.

- Bump MERO_PACKAGE_VERSION to 1.1.0.
- Don't use `-batch' option of gdb -- it suppresses gdb commands output.
  (Used to work fine with older gdb though.)
- Don't expect libmero.so.* file to end with MERO_PACKAGE_VERSION.
- program_from_core(): Don't treat single quote symbol as part of
  the file name.
- Add `hctl mero status' probe.

- configure.ac: Document `LT_VERSION` variable.

Change-Id: Iabf36cbc2891d897b73d6e911c65f781f4e0d93d

diff --git a/utils/m0reportbug b/utils/m0reportbug
--- a/utils/m0reportbug
+++ b/utils/m0reportbug
@@ -3,14 +3,14 @@ set -eu
 # set -x
 export PS4='+ [${FUNCNAME[0]:+${FUNCNAME[0]}:}${LINENO}] '
 
-VERSION=0.22.2
+VERSION=0.23
 
 IN_DIR=/var/mero # default value; overruled by CLI argument
 OUT_DATA_DIR=m0reportbug-data
 OUT_CORES_DIR=m0reportbug-cores
 OUT_TRACES_DIR=m0reportbug-traces
 REPORT=m0reportbug.txt # the file is created in $OUT_DATA_DIR/
-MERO_PACKAGE_VERSION=1.0.0 # must correspond to `M0_VERSION' in configure.ac
+MERO_PACKAGE_VERSION=1.1.0 # must correspond to `M0_VERSION' in configure.ac
 M0TRACES_MAX=20 # how many most recently modified m0trace files to collect
 M0TRACES_M0D_MAX=2 # additionally, collect that many m0trace files from each
                    # $IN_DIR/m0d-* directory
@@ -128,6 +128,7 @@ probes() {
         'systemctl status -l mero-kernel'
         'lctl dk'
         'hctl cluster status'
+        'hctl mero status'
         'hctl debug eq'
         'hctl debug cep'
         'find /var/mero'
@@ -223,7 +224,7 @@ _time() {
 
 program_from_core() {
     local core=$1
-    local prog=$(file $core | sed -En "s/.*, from '([^ ]+).*/\1/p")
+    local prog=$(file $core | sed -En "s/.*, from '([^ ']+).*/\1/p")
     if [ -n "$prog" ]; then
         ## $ file /var/mero/ios1/core.1271
         ## /var/mero/ios1/core.1271: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'm0d -e lnet:10.22.192.32@tcp:12345:42:401 -f <0x7200000000000001:4> -T ad -D db'
@@ -234,6 +235,7 @@ program_from_core() {
         prog=$(gdb -batch -nx -ex "core $core" 2>/dev/null |
                    sed -En "s/^Core was generated by \`([^ ']+).*/\\1/p")
     fi
+    [ -n "$prog" ] || warn "Cannot deduce name of program from \`$core'"
     basename $prog
 }
 
@@ -259,7 +261,7 @@ _path_rpm() {
     case $name in
         m0d|m0mkfs|m0trace|m0tracedump) echo "/usr/bin/$name";;
         m0addb2dump) echo "/usr/sbin/$name";;
-        libmero.so) echo "/usr/lib64/libmero.so.${MERO_PACKAGE_VERSION}";;
+        libmero.so) readlink -f /usr/lib64/libmero.so;;
         m0mero.ko) echo "/lib/module/$(uname -r)/kernel/fs/mero/$name";;
         m0ham|lt-m0ham) echo "/usr/sbin/$name";;
         m0ut|lt-m0ut)
@@ -292,7 +294,7 @@ _path_src() {
         m0addb2dump)
             [ -z "$subdir" ] || die "${FUNCNAME[0]}: Unexpected argument"
             echo "$src/addb2/$name";;
-        libmero.so) echo "$src/mero/.libs/libmero.so.${MERO_PACKAGE_VERSION}";;
+        libmero.so) readlink -f "$src/mero/.libs/libmero.so";;
         m0mero.ko) echo "$src/mero/$name";;
         m0ham|lt-m0ham) echo "$src/ha/.libs/$name";;
         m0ut|lt-m0ut) echo "$src/ut/.libs/$name";;
@@ -343,9 +345,10 @@ gdb_bt() {
     [ $# -eq 2 ] || die "Usage: ${FUNCNAME[0]} <prog> {<core>|<pid>}"
 
     [ -n "$1" ] || return 0 # do nothing if `prog' argument is empty
+    local libdir=$(dirname "$(path libmero.so)")
     {
         cat <<EOF
-echo "set solib-search-path .:$(dirname '$(path libmero.so)')"
+echo "set solib-search-path .:$libdir"
 set pagination off
 p "### bt"
 bt
@@ -356,7 +359,7 @@ thread apply all bt full
 p "### info sharedlibrary"
 info sharedlibrary
 EOF
-    } | $GDB -batch -nx $@ 2>&1 || true
+    } | $GDB -nx "$@" 2>&1 || true
     echo
 }
 
@@ -616,6 +619,17 @@ exit
 ###
 ### Date       Version Description
 ### ---------- ------- ----------------------------------------------------
+### 2017-08-13 0.23    * Bump MERO_PACKAGE_VERSION to 1.1.0.
+###                    * gdb_bt(): Don't use `-batch' option of gdb ---
+###                      it suppresses gdb commands output.
+###                      (Used to work fine with older gdb though.)
+###                    * _path_rpm(), _path_src(): Don't expect libmero.so.*
+###                      file to end with MERO_PACKAGE_VERSION --- libtool
+###                      uses its own version numbering algorithm.
+###                    * program_from_core(): Don't treat single quote symbol
+###                      as part of the file name.
+###                    * Add `hctl mero status' probe.
+###
 ### 2017-06-23 0.22.2  Disable `df -h' entirely.
 ###
 ### 2017-05-26 0.22.1  Set LC_ALL=C.
