scripts: redirect ST output to sandbox directories
* scripts/m0 (run-st): Set SANDBOX_DIR variable, unique for each system test.
* scripts/functions: Add `sandbox_init', `sandbox_fini'.
* Use `M0_SRC_DIR' instead of `M0_CORE_DIR', `MERO_CORE_ROOT', and `BROOT'.
* sss/st:
  - Restore previously disabled checks.
  - Fix the value of MKFS_OPTS: remove quote symbol from the name of stob
    directory.
* m0t1fs_dgmode_io.sh: Fix indentation.

Reference: MERO-1350
Reviewed-by: Dima Chumak <dmitriy.chumak@seagate.com>
Change-Id: I5ad9a21f54fd4519d6a70ba39fb74024062259b9

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -2,12 +2,27 @@
 
 die() { echo "$@" >&2; exit 1; }
 
+sandbox_init() {
+    [ -n "${SANDBOX_DIR:-}" ] || die 'SANDBOX_DIR: unbound variable'
+    rm -rf $SANDBOX_DIR
+    mkdir $SANDBOX_DIR
+    pushd $SANDBOX_DIR >/dev/null
+}
+
+sandbox_fini() {
+    [ -n "${SANDBOX_DIR:-}" ] || die 'SANDBOX_DIR: unbound variable'
+    popd >/dev/null
+    [ -n "${KEEP_SANDBOX:-}" ] || rm -r $SANDBOX_DIR
+}
+
 ### Example:
 ###     $ opcode M0_LAYOUT_OPCODE
 ###     92
 opcode() {
-	[ $# -eq 1 ] || die 'Invalid usage'
-	local NAME="$1"
-	grep -v '#pragma once' $M0_CORE_DIR/rpc/rpc_opcodes.h | cpp | \
-		awk "/$NAME/ {print \$3}" | tr -d ,
+    [ $# -eq 1 ] || die 'Invalid usage'
+    local NAME="$1"
+
+    [ -n "${M0_SRC_DIR:-}" ] || die 'M0_SRC_DIR: unbound variable'
+    grep -v '#pragma once' $M0_SRC_DIR/rpc/rpc_opcodes.h | cpp |
+        awk "/$NAME/ {print \$3}" | tr -d ,
 }
diff --git a/spiel/st b/spiel/st
--- a/spiel/st
+++ b/spiel/st
@@ -1,8 +1,8 @@
 #!/bin/bash
 set -eu
 
-#set -x
-export PS4='+ ${FUNCNAME[0]:+${FUNCNAME[0]}():}line ${LINENO}: '
+# set -x
+# export PS4='+ ${FUNCNAME[0]:+${FUNCNAME[0]}():}line ${LINENO}: '
 
 ## CAUTION: This path will be removed by superuser.
 SANDBOX_DIR=${SANDBOX_DIR:-/var/mero/sandbox.spiel-st}
@@ -14,15 +14,15 @@ TRACE_CONTEXT=${M0_TRACE_PRINT_CONTEXT:-}
 MAX_RPC_MSG_SIZE=163840
 TM_MIN_RECV_QUEUE_LEN=2
 DEV_NR=4
-DEV_SIZE=$((1024 *1024))
+DEV_SIZE=$((1024 * 1024))
 
-die() { echo "$@" >&2; exit 1; }
 error() { echo "$@" >&2; stop 1; }
 
-M0_CORE_DIR=`readlink -f $0`
-M0_CORE_DIR=${M0_CORE_DIR%/*/*}
+M0_SRC_DIR=`readlink -f $0`
+M0_SRC_DIR=${M0_SRC_DIR%/*/*}
 
-. $M0_CORE_DIR/m0t1fs/linux_kernel/st/common_service_fids_inc.sh
+. $M0_SRC_DIR/scripts/functions  # die, sandbox_init
+. $M0_SRC_DIR/m0t1fs/linux_kernel/st/common_service_fids_inc.sh
 
 ## Path to the file with configuration string for confd.
 CONF_FILE=$SANDBOX_DIR/conf.txt
@@ -52,9 +52,9 @@ EOF
 
 start() {
     # install "mero" Python module required by m0spiel tool
-    cd $M0_CORE_DIR/utils/spiel
+    cd $M0_SRC_DIR/utils/spiel
     python setup.py install > /dev/null || die 'Cannot install Python "mero" module'
-    cd $M0_CORE_DIR
+    cd $M0_SRC_DIR
     _init
     m0d_with_rms_start
 }
@@ -73,39 +73,26 @@ _init() {
     lnet_up
     modules_insert
     sandbox_init
-}
-
-_fini() {
-    sandbox_fini
-    modules_remove
-}
-
-sandbox_init() {
-    rm -rf $SANDBOX_DIR
-    mkdir -p $SANDBOX_DIR/mnt
+    mkdir $SANDBOX_DIR/mnt
     iosloopdevs
 }
 
-sandbox_fini() {
-    if [ -d $SANDBOX_DIR/mnt ]; then
-        rmdir $SANDBOX_DIR/mnt
-    fi
-    ## Note that the script does not delete $SANDBOX_DIR itself:
-    ## developers may want to analyze the logs contained there.
-    for i in $(seq 1 $DEV_NR)
-    do
+_fini() {
+    for i in $(seq 1 $DEV_NR); do
         losetup -d /dev/loop$i
     done
+    sandbox_fini
+    modules_remove
 }
 
 ### XXX Code duplication!
 ### There is an identical function in conf/st.
 ### TODO: Move this code to `scripts/functions'
 modules_insert() {
-    insmod $M0_CORE_DIR/extra-libs/gf-complete/src/linux_kernel/m0gf.ko ||
+    insmod $M0_SRC_DIR/extra-libs/gf-complete/src/linux_kernel/m0gf.ko ||
         die 'Inserting m0gf.ko failed'
 
-    insmod $M0_CORE_DIR/mero/m0mero.ko \
+    insmod $M0_SRC_DIR/mero/m0mero.ko \
     local_addr=$M0T1FS_ENDPOINT \
     max_rpc_msg_size=$MAX_RPC_MSG_SIZE \
     tm_recv_queue_min_len=$TM_MIN_RECV_QUEUE_LEN \
@@ -113,8 +100,8 @@ modules_insert() {
     ${TRACE_LEVEL:+trace_level=$TRACE_LEVEL} \
     ${TRACE_CONTEXT:+trace_print_context=$TRACE_CONTEXT} \
     || {
-    rmmod m0gf
-    die 'Inserting m0mero.ko failed'
+        rmmod m0gf
+        die 'Inserting m0mero.ko failed'
     }
 }
 
@@ -212,19 +199,19 @@ m0d_with_rms_start() {
     -m $MAX_RPC_MSG_SIZE -q $TM_MIN_RECV_QUEUE_LEN -c $CONF_FILE\
     -w 3 -P $PROF_OPT -f $PROC_FID -d $SANDBOX_DIR/disks.conf"
 
-    stub_confdb | $M0_CORE_DIR/utils/m0confgen >$CONF_FILE
+    stub_confdb | $M0_SRC_DIR/utils/m0confgen >$CONF_FILE
 
     echo "--- `date` ---" >>$SANDBOX_DIR/m0d.log
     cd $SANDBOX_DIR
 
     ## m0mkfs should be executed only once. It is usually executed
     ## during cluster initial setup.
-    echo $M0_CORE_DIR/utils/mkfs/m0mkfs $OPTS
-    $M0_CORE_DIR/utils/mkfs/m0mkfs $OPTS >>$SANDBOX_DIR/mkfs.log ||
+    echo $M0_SRC_DIR/utils/mkfs/m0mkfs $OPTS
+    $M0_SRC_DIR/utils/mkfs/m0mkfs $OPTS >>$SANDBOX_DIR/mkfs.log ||
     error 'm0mkfs failed'
 
-    echo $M0_CORE_DIR/mero/m0d $OPTS
-    $M0_CORE_DIR/mero/m0d $OPTS >>$SANDBOX_DIR/m0d.log 2>&1 &
+    echo $M0_SRC_DIR/mero/m0d $OPTS
+    $M0_SRC_DIR/mero/m0d $OPTS >>$SANDBOX_DIR/m0d.log 2>&1 &
     local PID=$!
     sleep 10
     kill -0 $PID 2>/dev/null ||
@@ -240,8 +227,8 @@ test_m0d_start() {
 
     cd $SANDBOX_DIR
 
-    echo $M0_CORE_DIR/mero/m0d $OPTS
-    $M0_CORE_DIR/mero/m0d $OPTS >>$SANDBOX_DIR/m0d.log 2>&1 &
+    echo $M0_SRC_DIR/mero/m0d $OPTS
+    $M0_SRC_DIR/mero/m0d $OPTS >>$SANDBOX_DIR/m0d.log 2>&1 &
     local PID=$!
     sleep 10
     kill -0 $PID 2>/dev/null ||
@@ -252,11 +239,11 @@ services_stop() { killall -q lt-m0d && wait || true; }
 
 export_vars() {
     export M0_SPIEL_OPTS="
-    -l $M0_CORE_DIR/mero/.libs/libmero.so --server $SERVER1_ENDPOINT
+    -l $M0_SRC_DIR/mero/.libs/libmero.so --server $SERVER1_ENDPOINT
     --client $SPIEL_ENDPOINT --rmservice $SERVER1_ENDPOINT"
 
     export M0_SPIEL_OPTS2="
-    -l $M0_CORE_DIR/mero/.libs/libmero.so --server $SERVER2_ENDPOINT
+    -l $M0_SRC_DIR/mero/.libs/libmero.so --server $SERVER2_ENDPOINT
     --client $SPIEL_ENDPOINT --rmservice $SERVER1_ENDPOINT"
 
     export FIDS_LIST="
@@ -307,7 +294,7 @@ HEALTH_GOOD, HEALTH_BAD, HEALTH_INACTIVE, HEALTH_UNKNOWN = range(4)
 }
 
 construct_db() {
-    $M0_CORE_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS <<EOF
+    $M0_SRC_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS <<EOF
 $FIDS_LIST
 N = 2
 K = 1
@@ -410,7 +397,7 @@ EOF
 }
 
 validate_health() {
-    $M0_CORE_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
+    $M0_SRC_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
 $FIDS_LIST
 $SERVICES
 $HEALTH
@@ -432,7 +419,7 @@ EOF
 }
 
 restart_services() {
-    $M0_CORE_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
+    $M0_SRC_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
 $FIDS_LIST
 $SERVICES
 
@@ -457,7 +444,7 @@ EOF
 }
 
 reconfig_process() {
-    $M0_CORE_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
+    $M0_SRC_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
 $FIDS_LIST
 
 if spiel.cmd_profile_set(str(fids['profile'])) != 0:
@@ -484,7 +471,7 @@ perform_io() {
 }
 
 fs_stats_fetch() {
-    $M0_CORE_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
+    $M0_SRC_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
 $FIDS_LIST
 
 if spiel.cmd_profile_set(str(fids['profile'])) != 0:
@@ -510,7 +497,7 @@ none $SANDBOX_DIR/mnt"
 }
 
 device_commands_check() {
-    $M0_CORE_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
+    $M0_SRC_DIR/utils/spiel/m0spiel $M0_SPIEL_OPTS2 <<EOF
 $FIDS_LIST
 
 if spiel.cmd_profile_set(str(fids['profile'])) != 0:
