ST: use `report_and_exit' function
Dear m0t1fs/linux_kernel/st/m0t1fs_*.sh system tests,
you know, those "Failed: <this and that> failed" messages in your output,
they actually mean something. You should not happily exit 0 in such cases
like if nothing happened.

+ scripts/st.d/07mount: Call st/m0mount instead of duplicating its options.
+ st/m0mount, st/m0d-fsync-test.sh: Remove $SANDBOX_DIR upon success.

Change-Id: I31828ff563ad1eaab45934543374170dce6c92ff

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -15,6 +15,21 @@ sandbox_fini() {
     [ -n "${KEEP_SANDBOX:-}" ] || rm -r $SANDBOX_DIR
 }
 
+report_and_exit() {
+    [ $# -eq 2 ] || die "${FUNCNAME[0]}: Invalid usage"
+    local name=$1
+    local rc=$2
+
+    if [ $rc -eq 0 ]; then
+        ## This message is used by Jenkins as a test success criteria;
+        ## it must appear on stdout.
+        echo "$name: test status: SUCCESS"
+    else
+        echo "$name: FAILURE $rc" >&2
+    fi
+    exit $rc
+}
+
 ### Similar to `source` builtin command with `set +eu` in effect.
 ###
 ### Vanilla `. /etc/rc.d/init.d/functions` will fail if either "errexit"
@@ -30,7 +45,7 @@ source+eu() {
 ###     $ opcode M0_LAYOUT_OPCODE
 ###     92
 opcode() {
-    [ $# -eq 1 ] || die 'Invalid usage'
+    [ $# -eq 1 ] || die "${FUNCNAME[0]}: Invalid usage"
     local NAME="$1"
 
     [ -n "${M0_SRC_DIR:-}" ] || die 'M0_SRC_DIR: unbound variable'
