scripts/m0mount: wait for confd to start
m0mount waits only for IO services to start. This leads to a race when
an m0d is terminated before confd establishes connection to the m0d. In
this situation confd is stuck on connecting with the endless timeout.
This patch adds wait for confd to start before launching mount(8).
Therefore, m0mount doesn't stop m0d's before confd establishes all
necessary connections.

Change-Id: Ibb5bdb6f0b36443e91c971bec84c70c49b151a3f

diff --git a/scripts/m0mount b/scripts/m0mount
--- a/scripts/m0mount
+++ b/scripts/m0mount
@@ -661,6 +661,34 @@ $M0D $STOB_PARAMS -D $DDIR/db -S $DDIR/stobs -A linuxstob:$DDIR/addb-stobs \
 	STARTED[$H]=$H
 }
 
+function wait_for_services ()
+{
+	local LOG_FILES="$1"
+	local NR=$2
+
+	local log_nr=`echo $LOG_FILES | wc -w`
+	if [ $NR -ne $log_nr ]; then
+		echo "ERROR: Number of services ($NR) doesn't equal to number of log files ($log_nr)"
+		echo "List of the log files: $LOG_FILES"
+		return 1
+	fi
+
+	while true; do
+		local STARTED_NR=`cat $LOG_FILES | grep CTRL | wc -l`
+		echo "Started $STARTED_NR (of $NR) services..."
+		[ $STARTED_NR -ge $NR ] && break
+		local START_ERROR=`cat $LOG_FILES | grep ERROR | wc -l`
+		if [ $START_ERROR -gt 0 ]; then
+			echo "Failed to start Mero!"
+			cat $LOG_FILES | grep ERROR
+			return 1
+		fi
+		l_do sleep 5
+	done
+
+	return 0
+}
+
 function start_servers ()
 {
 	local i
@@ -703,19 +731,10 @@ function start_servers ()
 		fi
 	fi
 
-	echo "Wait for the services to start up..."
-	while true; do
-		local STARTED_NR=`cat ${SLOG}[0-9]*.log | grep CTRL | wc -l`
-		echo "Started $STARTED_NR (of $SERVICES_NR) services..."
-		[ $STARTED_NR -ge $SERVICES_NR ] && break
-		local START_ERROR=`cat ${SLOG}[0-9]*.log | grep ERROR | wc -l`
-		if [ $START_ERROR -gt 0 ]; then
-			echo "Failed to start Mero!"
-			cat ${SLOG}[0-9]*.log | grep ERROR
-			return 1
-		fi
-		l_do sleep 5
-	done
+	echo "Wait for the IO services to start up..."
+	wait_for_services "${SLOG}[0-9]*.log" $SERVICES_NR || return 1
+	echo "Wait for the confd service to start up..."
+	wait_for_services "${SLOG}-confd.log" 1 || return 1
 
 	return 0
 }
